In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk

In [2]:
df=pd.read_csv("breast_cancer.csv")

In [3]:
df=df.iloc[:,:-1]

In [4]:
df.shape

(569, 31)

In [5]:
x=df.iloc[:,2:].values
y=df.diagnosis.values

In [6]:
print(x[:5])
print(y[:5])

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2.839e-01 2.414e-01
  1.052e-01 2.597e-01 9.7

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=500)

In [9]:
x_train.shape

(455, 29)

In [10]:
x_test.shape

(114, 29)

In [11]:
y_train.shape

(455,)

In [12]:
y_test.shape

(114,)

In [13]:
(y_train == 'M').sum()

np.int64(177)

In [14]:
(y_train=='B').sum()

np.int64(278)

In [15]:
278/len(y_train)  # Baseline model of accuracy =(more number of occurrences)/total data elements

0.610989010989011

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [17]:
baseline_pred=["B"] *len(y_train) # baseline will have beningn for everything

In [18]:
accuracy_score(y_train,baseline_pred) # takes actual and predicted as 2 arguments

0.610989010989011

In [19]:
confusion_matrix(y_train,baseline_pred)# takes actual and predicted as 2 arguments

array([[278,   0],
       [177,   0]])

In [20]:
print(classification_report(y_train,baseline_pred))

              precision    recall  f1-score   support

           B       0.61      1.00      0.76       278
           M       0.00      0.00      0.00       177

    accuracy                           0.61       455
   macro avg       0.31      0.50      0.38       455
weighted avg       0.37      0.61      0.46       455



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
nb_model=GaussianNB()

In [23]:
nb_model.fit(x_train,y_train)

GaussianNB()

In [24]:
print(x_train)

[[1.959e+01 1.815e+01 1.307e+02 ... 6.810e-01 2.247e-01 3.643e-01]
 [1.132e+01 2.708e+01 7.176e+01 ... 1.089e-01 2.083e-02 2.849e-01]
 [9.173e+00 1.386e+01 5.920e+01 ... 1.397e-01 5.087e-02 3.282e-01]
 ...
 [1.481e+01 1.470e+01 9.466e+01 ... 1.101e-01 7.955e-02 2.334e-01]
 [1.289e+01 1.312e+01 8.189e+01 ... 1.186e-01 5.366e-02 2.309e-01]
 [9.742e+00 1.567e+01 6.150e+01 ... 4.043e-02 5.159e-02 2.841e-01]]


In [25]:
nb_model.score(x_train,y_train)

0.9340659340659341

In [26]:
nb_model.score(x_test,y_test)

0.9736842105263158

In [27]:
#confusion_matrix for training data
confusion_matrix(y_train,nb_model.predict(x_train))

array([[270,   8],
       [ 22, 155]])

In [28]:
#confusion_matrix for test data
confusion_matrix(y_test,nb_model.predict(x_test))

array([[78,  1],
       [ 2, 33]])

In [29]:
print(classification_report(y_train,nb_model.predict(x_train)))

              precision    recall  f1-score   support

           B       0.92      0.97      0.95       278
           M       0.95      0.88      0.91       177

    accuracy                           0.93       455
   macro avg       0.94      0.92      0.93       455
weighted avg       0.93      0.93      0.93       455



In [30]:
print(classification_report(y_test,nb_model.predict(x_test)))

              precision    recall  f1-score   support

           B       0.97      0.99      0.98        79
           M       0.97      0.94      0.96        35

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [31]:
nb_model.predict_proba(x_train) # benign>0.5 otherwise if <0.5 then malignant{ first column is benign and secon is malignant according to aplphanumerical order}

array([[4.84020645e-089, 1.00000000e+000],
       [1.00000000e+000, 1.84881026e-014],
       [1.00000000e+000, 1.29452007e-014],
       [6.43102697e-092, 1.00000000e+000],
       [2.63860886e-008, 9.99999974e-001],
       [1.00000000e+000, 3.58617721e-012],
       [4.61324228e-008, 9.99999954e-001],
       [1.00000000e+000, 2.02873034e-015],
       [9.99999832e-001, 1.68465735e-007],
       [1.00000000e+000, 1.86119452e-013],
       [9.99524118e-001, 4.75882486e-004],
       [2.50110485e-014, 1.00000000e+000],
       [1.00000000e+000, 1.24035753e-013],
       [9.20487763e-001, 7.95122369e-002],
       [5.15532227e-079, 1.00000000e+000],
       [2.95254359e-005, 9.99970475e-001],
       [6.71236185e-027, 1.00000000e+000],
       [2.55192645e-004, 9.99744807e-001],
       [1.00000000e+000, 1.89143118e-012],
       [9.99999998e-001, 1.74541690e-009],
       [1.00000000e+000, 2.81101863e-013],
       [1.00000000e+000, 8.69525897e-014],
       [3.83313399e-253, 1.00000000e+000],
       [1.0

In [32]:
nb_model.predict(x_train)[:5]

array(['M', 'B', 'B', 'M', 'M'], dtype='<U1')

In [33]:
np.set_printoptions(suppress= True)
nb_model.predict_proba(x_train)[:5]

array([[0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.00000003, 0.99999997]])

In [34]:
nb_model.predict_proba(x_train)[:,1]>0.4

array([ True, False, False,  True,  True, False,  True, False, False,
       False, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True, False,  True,
        True,  True, False, False, False, False, False, False,  True,
       False,  True,  True, False, False, False, False,  True,  True,
       False, False, False, False,  True,  True, False,  True, False,
       False, False, False,  True,  True, False, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False,  True, False, False, False,  True, False,
        True, False, False, False, False, False,  True, False, False,
        True,  True, False,  True, False, False, False,  True, False,
       False,  True, False, False, False, False, False,  True,  True,
        True, False,

In [35]:
pred=nb_model.predict_proba(x_train)[:,1] >0.25

In [36]:
confusion_matrix(y_train =='M',pred)

array([[269,   9],
       [ 19, 158]])

In [37]:
test_pred=nb_model.predict_proba(x_test)[:,1] >0.25

In [38]:
confusion_matrix(y_test =='M',test_pred)

array([[78,  1],
       [ 2, 33]])